name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'EApartmentManagerBackend/**'

env:
  AZURE_WEBAPP_NAME: "app-eapartment-api-germanywestcentral-001"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore EApartmentManagerBackend/ApartmentApi

    - name: Run Unit Tests
      run: dotnet test EApartmentManagerBackend/ApartmentApiTests

    - name: Build
      run: dotnet build EApartmentManagerBackend/ApartmentApi --configuration Release --no-restore

    - name: Publish
      run: dotnet publish EApartmentManagerBackend/ApartmentApi --configuration Release --output ./EApartmentManagerBackend/ApartmentApi/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
        package: ./EApartmentManagerBackend/ApartmentApi/publish
